# env:
env_config:
  env_name: Lift
  robots: [Panda]               # load a Sawyer robot and a Panda robot
  has_renderer: False                      # no on-screen rendering
  has_offscreen_renderer: True             # off-screen rendering needed for image obs
  control_freq: 20                         # 20 hz control for applied actions
  horizon: 500                             # each episode terminates after 200 steps
  use_object_obs: False                    # don't provide object observations to agent
  use_camera_obs: True                     # provide image observations to agent
  camera_names: "agentview"                # use "agentview" camera for observations
  camera_heights: 84                       # image height
  camera_widths: 84                        # image width
  reward_shaping: True                     # use a dense reward signal for learning

# Note that the default encoder for visual observations outputs a 1024D vector; for other embedding sizes an additional fully-connected layer is used
taskset_name: robosuite
info_names: []
symbolic_env: False
observation_shapes: 
  image_84: [3, 84, 84]
action_name: "action"
action_size: 
action_repeat: 1
episodes: 1000
bit_depth: 5
noise_scale: 0.
add_noise: False
noisy_background: False