# train:
experience_replay:
- ../../../../../dataset_AdRobotics/DMControlSuite/Finger-spin/JSAI/Expert_demonstration/optimal_demonstrations
validation_data:
- ../../../../../dataset_AdRobotics/DMControlSuite/Finger-spin/demonstration_for_RSSM/uniform_demonstrations

n_episode: 

# Original implementation has an unlimited buffer size, but 1 million is the max experience collected anyway
experience_size: 1_000_000
n_crop: 
noise_scales:
pca_scales:
dh_base:
dw_base:
action_noise: 0.3
train_iteration: 10_000
seed_episodes: 
collect_interval: 
batch_size: 50
chunk_size: 50
random_sampling: True
update_policy: True

use_amp: True

backprop_policy_grad: False
rssm:
  load: False
  model_path: 
  fix: False
