# main:
experiment_name: 
tags:
log_dir:
algo: dreamer
seed: 0
disable_cuda: False
device: cuda:0
test: False
test_interval: 25
test_episodes: 5
checkpoint_interval: 100
checkpoint_experience: False
models: ""
render: False

mlflow: False
wandb : True
git_hash: