# train:
experience_replay: ""
validation_data:
n_episode: 

# Original implementation has an unlimited buffer size, but 1 million is the max experience collected anyway
experience_size: 1_000_000
n_crop: 
noise_scales: 
pca_scales: 
dh_base: 
dw_base: 
action_noise: 0.3
train_iteration: 100_000
seed_episodes: 5
collect_interval: 100
batch_size: 50
chunk_size: 50
update_policy: False

use_amp: True

backprop_policy_grad: False
rssm:
  load: False
  model_path: 
  fix: False

